services:
  scout:
    image: samply/scout
    build: .
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      FHIR_BASE_URL: http://host.docker.internal:8081/fhir