services:
  scout:
    image: samply/scout
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    configs:
      - scout.toml

configs:
  scout.toml:
    content: |
      fhir_base_url = "http://host.docker.internal:8081/fhir"
