name: Dioxus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-binstall
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - name: Install Dioxus CLI
      run: cargo binstall dioxus-cli
    - name: Create stub tailwind.css
      run:  touch assets/tailwind.css
    - name: Check cargo fmt
      run: cargo fmt --check
    - name: Check dioxus formatting
      run: dx fmt --check
    - name: Build
      run: dx build
    - name: Run tests
      run: cargo test
