name: Docker

on:
  # Uncomment to enable nightly builds
  # schedule:
  #   - cron: 0 0 * * *
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:

jobs:
  docker:
    uses: ./.github/workflows/samply-docker.yml
    with:
      image-name: samply/scout
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
